"use client";
import type { HumanAction } from "./market-v10";
export type ActionLimits = { bounds?:Record<string,{min:number;max:number}>; [key:string]:unknown };
const budgets=[['service_budget_cents','服务投入'],['capacity_investment_cents','企业扩产'],['resilience_budget_cents','企业韧性投入'],['threshold_project_contribution_cents','阈值公共项目投入'],['repair_budget_cents','事故维修投入']] as const;
const optionalFields=['threshold_project_contribution_cents','mutual_aid_partner_company_id','mutual_aid_capacity_offer_orders','mutual_aid_capacity_request_orders','price_coordination_partner_company_id','price_coordination_target_cents','contract_quantity_orders','contract_duration_rounds','contract_bid_cents'];
export function advancedEconomicFields(action:HumanAction) {return Object.fromEntries(optionalFields.filter(k=>action.advanced?.[k]!==undefined&&action.advanced[k]!=="").map(k=>[k,action.advanced![k]]));}
export function AdvancedActions({action,change,limits={},disabled}:{action:HumanAction;change:(action:HumanAction)=>void;limits?:ActionLimits;disabled:boolean}) {
  const values=action.advanced??{};
  const patch=(key:string,value:string|number)=>change({...action,advanced:{...values,[key]:value}});
  const enabled=(key:string)=>key==='capacity_investment_cents'?limits.capacity_investment_enabled!==false:key==='resilience_budget_cents'?limits.resilience_investment_enabled!==false:key==='threshold_project_contribution_cents'?limits.threshold_project_contribution_enabled===true:true;
  return <details className="advanced-actions"><summary>高级经营、合作与通信</summary><fieldset disabled={disabled}><legend>预算与事故</legend><p>以下金额单位为元，提交时转为分；实际执行仍受现金及当轮能力限制。</p><div className="research-selectors">{budgets.map(([key,label])=><label key={key}>{label}（元）<input aria-label={`${label}（元）`} type="number" min={0} max={(limits.bounds?.[key]?.max??10000000)/100} step={1} disabled={!enabled(key)} value={Number(values[key]??0)/100} onChange={e=>patch(key,Math.max(0,Math.round(Number(e.target.value)*100)))}/></label>)}<label>事故处理<select aria-label="事故处理" value={values.incident_mode??"wait"} onChange={e=>patch('incident_mode',e.target.value)}><option value="wait">等待</option><option value="partial_repair">部分修复</option><option value="full_repair">完整修复</option></select></label></div>
    {limits.supply_contract_enabled===true&&<section><h3>主供应商长期预留合同</h3><p>预付采购、锁定单价及优先配给；少于承诺量下单将终止合同，供给中断记录缺约，不保证无条件交货。</p><div className="research-selectors">{[['contract_quantity_orders','每轮预留数量',10000],['contract_duration_rounds','合同期限（2至5轮，0为不提出）',5],['contract_bid_cents','议价出价（分）',100000]].map(([key,label,max])=><label key={String(key)}>{String(label)}<input aria-label={String(label)} type="number" min={0} max={Number(max)} value={Number(values[String(key)]??0)} onChange={e=>patch(String(key),Math.max(0,Math.trunc(Number(e.target.value))))}/></label>)}</div></section>}
    <legend>双边互助</legend><p>双方同轮相互指名且存在供需、可用产能才成交。</p><div className="research-selectors"><label>互助对象<select aria-label="互助对象" value={values.mutual_aid_partner_company_id??""} onChange={e=>{const next:Record<string,string|number>={...values,mutual_aid_partner_company_id:e.target.value};if(!e.target.value){Object.assign(next,{mutual_aid_capacity_offer_orders:0,mutual_aid_capacity_request_orders:0});}change({...action,advanced:next});}}><option value="">不发起互助</option>{Array.isArray(limits.mutual_aid_eligible_partners)&&limits.mutual_aid_eligible_partners.map(id=><option key={String(id)}>{String(id)}</option>)}</select></label>{[['mutual_aid_capacity_offer_orders','提供代工单数'],['mutual_aid_capacity_request_orders','请求代工单数']].map(([key,label])=><label key={key}>{label}<input aria-label={label} type="number" min={0} max={limits.bounds?.[key]?.max??10000} disabled={!values.mutual_aid_partner_company_id} value={Number(values[key]??0)} onChange={e=>patch(key,Math.max(0,Math.trunc(Number(e.target.value))))}/></label>)}</div>
    <details><summary>价格协调实验动作</summary><p>仅为合成市场研究动作，可能被监管调查和罚款，不作为经营建议。</p><div className="research-selectors"><label>协调对象<select aria-label="协调对象" value={values.price_coordination_partner_company_id??""} onChange={e=>{const next:Record<string,string|number>={...values,price_coordination_partner_company_id:e.target.value};if(!e.target.value)delete next.price_coordination_target_cents;change({...action,advanced:next});}}><option value="">不提出协调</option>{Array.isArray(limits.price_coordination_eligible_partners)&&limits.price_coordination_eligible_partners.map(id=><option key={String(id)}>{String(id)}</option>)}</select></label><label>目标价格（元）<input aria-label="目标价格（元）" type="number" disabled={!values.price_coordination_partner_company_id} min={0} value={Number(values.price_coordination_target_cents??0)/100} onChange={e=>patch('price_coordination_target_cents',Math.round(Number(e.target.value)*100))}/></label></div></details>
    <legend>本轮消息</legend><p>通信开启时发送；消息不自动变为经济承诺或成交。</p><label>公开消息<textarea aria-label="公开消息" maxLength={500} value={action.publicMessage??""} onChange={e=>change({...action,publicMessage:e.target.value})}/></label><div className="research-selectors"><label>私信对象<select aria-label="私信对象" value={action.messageRecipient??""} onChange={e=>change({...action,messageRecipient:e.target.value})}><option value="">不发私信</option>{Array.isArray(limits.mutual_aid_eligible_partners)&&limits.mutual_aid_eligible_partners.map(id=><option key={String(id)}>{String(id)}</option>)}</select></label><label>私信内容<textarea aria-label="私信内容" maxLength={500} disabled={!action.messageRecipient} value={action.privateMessage??""} onChange={e=>change({...action,privateMessage:e.target.value})}/></label></div>
  </fieldset></details>;
}
