"use client";
import type {ReactNode} from 'react';
type RobustEvidence={beliefs:Record<string,{observations:number;probabilities:number[];expected_change:number;calibration:{n:number;mean_relative_error:number|null;flat_relative_error:number|null;interval_samples:number;empirical_coverage:number|null}}>;learning_enabled:boolean;response_enabled:boolean;response_complete:boolean;response_passes:number;nominal_choice:string;choice_changed:boolean;validation_profiles:number;response_profiles:{id:string;changed_actors:string[];profile:Record<string,unknown>}[];sensitivity:{same_choice_fraction:number;pareto_dominators:string[];scope:string;perturbations:{component:string;factor:number;selected:string}[]}|null;scope:string};
type Check={complete:boolean;restricted_pure_nash:boolean|null;deviation_gains:Record<string,number>;profile:Record<string,string>;scope?:string;private_deviation_gains?:Record<string,number>;participation_check_complete?:boolean};
type Advice={candidate_coverage?:{unsearched_or_equivalent:string[];scope:string};recommended_label:string;recommended_id:string;rationale:string;disposition:string;source_round:number;company_count:number;actor_count:number;objective:{goal:string;phase:string;phase_reason:string;weights:Record<string,number>;cash_floor_cents:number;risk_aversion:number};facts:Record<string,number>;search:{used_steps:number;step_budget:number;evaluated_candidates:number;horizon:number;elapsed_seconds:number;discovery_scenarios:number[];validation_scenarios:number[]};rankings:{candidate:{id:string;label:string};score:number;expected:number;tail_mean:number;safe:boolean;metrics:Record<string,number>;contributions:Record<string,number>}[];validation:{id:string;score:number;mean_gain:number;sample_range:number[];positive_samples:number;paired_gains:number[]}[];mechanisms:{name:string;enabled:boolean;simulation:string;search:string;assumption:string}[];diagnostics:{status:string;scope:string;recommendation_check?:Check;equilibrium?:Check;joint_welfare?:Check;local_structure?:{status:string;actors?:string[];payoffs?:number[][][];prisoners_dilemma?:boolean;coordination?:boolean;free_riding_incentive?:boolean;withdrawal_private_gain_cents?:number;withdrawal_welfare_change_cents?:number;scope:string}}|null;backtest:{scope:string;paired_utility_gains:number[];profit_gain_cents:number;welfare_gain_cents:number;prediction_profit_error_cents:number}|null;limitations:string[];failure_conditions:string[];action:Record<string,unknown>};
export const goalLabels:Record<string,string>={company:'公司阶段目标',profit:'公司利润',welfare:'社会福利（本公司单边行动）',balanced:'利润与福利平衡',custom:'自定义权重'};
export const phaseLabels:Record<string,string>={auto:'自动判断',survival:'生存保全',expansion:'扩张',mature:'成熟稳健',catch_up:'落后追赶',closing:'临近结束'};
export const metricLabels:Record<string,string>={profit:'利润',welfare:'福利',cash:'现金',share:'份额',capacity:'产能',resilience:'韧性'};
const n=(x:number|undefined)=>x===undefined?'未计算':Number(x.toFixed(4)).toLocaleString('zh-CN');
const money=(x:number)=>`¥${(x/100).toLocaleString('zh-CN',{maximumFractionDigits:2})}`;
function Table({headers,rows}:{headers:string[];rows:ReactNode[][]}){return <div className="v10-table-scroll"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table></div>;}
function Deviation({title,check}:{title:string;check?:Check}){return <section><h3>{title}</h3>{!check?<p>未执行。</p>:<><p>{check.complete?(check.restricted_pure_nash?'在已检查有限策略、期限与情景内，各方没有获利偏离。':'已发现单边获利偏离，该联合策略不满足已检查集合内的纯纳什条件。'):'分配给本项的计算预算不足，未完整检查，不能判断均衡。'}</p><Table headers={['主体','候选策略','单边可改善效用']} rows={Object.entries(check.profile).map(([id,p])=>[id,p,n(check.deviation_gains[id])])}/></>}</section>;}
export function AdvisorResult({value}:{value:unknown}){
 const r=value as Advice;const selected=r.rankings.find(x=>x.candidate.id===r.recommended_id);const d=r.diagnostics;
 const robust=(value as {v17?:RobustEvidence}).v17;
 return <article className="advisor-v16"><div className="theory-note"><strong>{r.recommended_label}</strong><p>{r.rationale}</p><p>目标：{goalLabels[r.objective.goal]}；阶段：{phaseLabels[r.objective.phase]}。{r.objective.phase_reason}。</p></div>
 {robust&&<section aria-label="v17反击与学习证据"><h3>对手反击怎样影响最终建议</h3><p>{robust.response_enabled?(robust.response_complete?'已完成配置的反击搜索，并在反击集合上重新验证入围动作。':'反击检查未完成，本次退回基线；基线也不保证盈利。'):'反击搜索已关闭，本次仅用于消融对照。'}搜索初选 {robust.nominal_choice} → 最终 {r.recommended_id}，{robust.choice_changed?'选择发生变化':'选择未变'}。共同验证{robust.validation_profiles}组响应，各组使用相同的新冲击情景。</p><p>{robust.scope}</p><details><summary>查看每个入围动作引发的反应</summary><Table headers={['入围动作','改选策略的主体']} rows={robust.response_profiles.map(p=>[p.id,p.changed_actors.join('、')||'无'])}/><pre>{JSON.stringify(robust.response_profiles,null,2)}</pre></details><h3>对手预测：已观察到什么</h3><p>公开历史学习{robust.learning_enabled?'开启':'关闭'}。使用带遗忘的价格变化计数，不读取对手现金或私有成本；无历史时依赖先验。表内误差来自逐时点预测；残差区间仅在至少8个既往误差后计算。</p><Table headers={['对手','历史变化样本','降/稳/涨概率','预计变化','预测相对误差','沿用上次价格误差','区间实测覆盖']} rows={Object.entries(robust.beliefs).map(([a,b])=>[a,b.observations,b.probabilities.map(p=>`${n(p*100)}%`).join(' / '),`${n(b.expected_change*100)}%`,b.calibration.mean_relative_error===null?'无历史评估':`${n(b.calibration.mean_relative_error*100)}%`,b.calibration.flat_relative_error===null?'无历史评估':`${n(b.calibration.flat_relative_error*100)}%`,b.calibration.empirical_coverage===null?'样本不足':`${n(b.calibration.empirical_coverage*100)}%（${b.calibration.interval_samples}次）`])}/><p>历史覆盖率不是未来覆盖保证；趋势变化或隐藏策略会使预测失效。</p><h3>目标权重是否敏感</h3>{robust.sensitivity?<><p>12次权重扰动中，{n(robust.sensitivity.same_choice_fraction*100)}%保持相同选择。{robust.sensitivity.scope}</p><p>按各维度平均值检查的帕累托支配候选：{robust.sensitivity.pareto_dominators.join('、')||'未发现'}。此检查不包含尾部风险和样本外结果。</p><details><summary>逐项权重扰动结果</summary><Table headers={['维度','扰动系数','选择']} rows={robust.sensitivity.perturbations.map(p=>[metricLabels[p.component],p.factor,p.selected])}/></details></>:<p>验证未完成，未生成权重稳健性结论。</p>}</section>}
 <h3>本轮建议怎么做</h3><Table headers={['动作','具体值']} rows={Object.entries({price_cents:'销售价格',procurement_quantity_orders:'采购数量',contract_duration_rounds:'合同轮数',advertising_budget_cents:'广告预算',service_budget_cents:'服务预算',capacity_investment_cents:'扩产投入',resilience_budget_cents:'韧性投入',shared_resilience_contribution_cents:'公共韧性贡献',threshold_project_contribution_cents:'门槛项目贡献'}).flatMap(([k,label])=>typeof r.action[k]==='number'?[[label,k.endsWith('_cents')?money(r.action[k] as number):n(r.action[k] as number)]]:[])}/>
 <h3>观察事实与计算范围</h3><p>源市场第{r.source_round}轮，{r.company_count}家公司，共{r.actor_count}个决策主体。当前现金{money(r.facts.cash_cents)}，现金底线{money(r.objective.cash_floor_cents)}。</p><p>评估{r.search.evaluated_candidates}个候选、预测{r.search.horizon}轮；使用{r.search.used_steps}/{r.search.step_budget}步引擎计算，耗时{n(r.search.elapsed_seconds)}秒。搜索与验证采用不同情景。最优性仅限已搜索范围。</p>
 {r.candidate_coverage&&<p>本次未单独搜索：{r.candidate_coverage.unsearched_or_equivalent.join('、')}。{r.candidate_coverage.scope}</p>}
 <h3>为什么选择它：目标分解</h3><Table headers={['目标维度','权重','候选的效用贡献']} rows={Object.entries(r.objective.weights).map(([k,w])=>[metricLabels[k],`${n(w*100)}%`,n(selected?.contributions[k])])}/><p>效用贡献使用固定尺度，不能把分数当作人民币；利润/现金及资产指标是偏好维度，福利按引擎独立核算。</p>
 {selected&&<p>搜索评分 = 平均效用 {n(selected.expected)} − 风险权重 {n(r.objective.risk_aversion)} ×（平均效用 − 最差四分位样本均值 {n(selected.tail_mean)}）= {n(selected.score)}。最终从通过独立验证的候选中按验证评分选择。</p>}
 <h3>替代方案与独立验证</h3><Table headers={['候选','搜索效用','验证效用','预测利润','预测福利','样本约束','验证差值范围']} rows={r.rankings.map(x=>{const v=r.validation.find(v=>v.id===x.candidate.id);return [x.candidate.label+(x.candidate.id===r.recommended_id?' ✓':''),n(x.score),v?n(v.score):'未计算',money(x.metrics.profit),money(x.metrics.welfare),x.safe?'满足':'不满足',v?v.sample_range.map(n).join(' 至 '):x.candidate.id==='baseline'?'比较基准':'未独立验证'];})}/><p>差值范围是验证样本最小值到最大值，不是置信区间；未验证的候选不能仅凭搜索得分晋级。</p>
 <h3>考虑了哪些市场机制</h3><Table headers={['机制','状态','搜索范围','建模假设']} rows={r.mechanisms.map(m=>[m.name,m.enabled?m.simulation:'未启用',m.search,m.assumption])}/>
 <h3>博弈论依据与稳定性</h3><p>{d?.scope||'本次关闭了多人诊断。'}</p><Deviation title="推荐方案与其他角色基线：偏离检查" check={d?.recommendation_check}/><details><summary>搜索得到的多人稳定性候选</summary><Deviation title="多人候选联合策略" check={d?.equilibrium}/></details>
 {d?.local_structure&&<p>局部贡献博弈：{d.local_structure.status==='evaluated'?`囚徒困境条件${d.local_structure.prisoners_dilemma?'成立':'未满足'}；协调条件${d.local_structure.coordination?'成立':'未满足'}；搭便车激励${d.local_structure.free_riding_incentive?'存在':'未检出'}。`:'预算不足，未计算。'}{d.local_structure.scope}</p>}
 {d?.local_structure?.payoffs&&<details><summary>局部博弈的收益表与判定依据</summary><p>{d.local_structure.actors?.join(' / ')} 的折现私有利润；每格依次为两家企业收益。其他主体策略固定。</p><Table headers={['本方 / 对方','贡献','不贡献']} rows={d.local_structure.payoffs.map((row,i)=>[i===0?'贡献':'不贡献',...row.map(cell=>cell.map(money).join(' / '))])}/><p>囚徒困境要求双方各自的 T（独自不贡献）&gt;R（共同贡献）&gt;P（都不贡献）&gt;S（独自贡献）。搭便车还检查单方退出是否增加私益并减少总福利。</p><p>单方退出私益变化 {money(d.local_structure.withdrawal_private_gain_cents||0)}；总福利变化 {money(d.local_structure.withdrawal_welfare_change_cents||0)}。</p></details>}
 {d?.joint_welfare&&<details><summary>联合福利协调方案与自愿参与限制</summary><p>{d.joint_welfare.scope}</p><p>各方私有目标偏离检查：{d.joint_welfare.participation_check_complete?'完成':'未完成，不能假定自愿接受'}。</p><Table headers={['主体','联合方案','私有目标可获利偏离']} rows={Object.entries(d.joint_welfare.profile).map(([a,p])=>[a,p,n(d.joint_welfare?.private_deviation_gains?.[a])])}/></details>}
 <h3>独立市场执行对照</h3>{r.backtest?<><p>{r.backtest.scope}</p><Table headers={['企业利润差','总福利差','各样本目标差','利润预测误差']} rows={[[money(r.backtest.profit_gain_cents),money(r.backtest.welfare_gain_cents),r.backtest.paired_utility_gains.map(n).join(' / '),money(r.backtest.prediction_profit_error_cents)]]}/></>:<p>本次未执行事后对照。</p>}
 <h3>可能失效的条件</h3><ul>{r.failure_conditions.map(x=><li key={x}>{x}</li>)}</ul><details><summary>假设与尚未证明的部分</summary><ul>{r.limitations.map(x=><li key={x}>{x}</li>)}</ul></details><details><summary>可执行动作（完整实验导出包含该动作与证据）</summary><pre>{JSON.stringify(r.action,null,2)}</pre></details>
 </article>;
}
