"use client";
type Result={version:string;mode:string;disposition:string;rationale:string;source_round:number;company_count:number;recommended_id:string;objective:{goal:string;phase:string;weights:Record<string,number>;cash_floor_cents:number};draft_action:Record<string,unknown>;action:Record<string,unknown>;continuation:string;response_model:string;model_sha256:string;search:{elapsed_seconds:number;used_steps:number;step_budget:number;complete:boolean};validation:{horizon:number;mean_gain:number;lower_bound:number;negative_samples:number;safe:boolean;pass_gate:boolean}[];rankings:{candidate:{id:string};contributions:Record<string,number>;metrics:Record<string,number>}[];limitations:string[];candidates:{id:string;label:string;change:Record<string,unknown>}[]};
const metrics:Record<string,string>={profit:'公司利润',welfare:'社会福利',cash:'期末现金变化',share:'份额变化',capacity:'产能变化',resilience:'韧性变化'};
const goals:Record<string,string>={company:'公司阶段目标',profit:'公司利润',welfare:'社会福利',balanced:'利润与福利平衡',custom:'自定义权重'};
const phases:Record<string,string>={survival:'生存保全',expansion:'扩张',mature:'成熟稳健',catch_up:'落后追赶',closing:'临近结束'};
export function ReliableAdvisorResult({value}:{value:unknown}){
 const r=value as Result;const changes=Object.keys(r.action).filter(k=>!['action_id','strategy_summary'].includes(k)&&JSON.stringify(r.action[k])!==JSON.stringify(r.draft_action[k]));
 const original=r.rankings.find(x=>x.candidate.id==='agent_draft');const selected=r.rankings.find(x=>x.candidate.id===r.recommended_id);
 return <article aria-label="原计划改进建议"><div className="theory-note"><strong>{r.disposition==='abstain'?'保留原计划':'建议局部修改原计划'}</strong><p>{r.rationale}</p><p>第{r.source_round}轮，{r.company_count}家公司；{r.mode==='interactive'?'交互模式：一轮预测':'研究模式：三轮预测并以五轮验证'}。</p></div>
 <p>目标：{goals[r.objective.goal]||r.objective.goal}；阶段：{phases[r.objective.phase]||r.objective.phase}；现金底线 ¥{(r.objective.cash_floor_cents/100).toFixed(2)}。</p>
 {original&&selected&&<><h3>为什么符合当前目标</h3><p>下表是发现情景中的预测均值差及其加权效用贡献。投入可能降低利润，同时提高其他阶段目标；效用增益不等于人民币收益。最终是否修改还要通过下面的独立验证。</p><table><thead><tr><th>目标维度</th><th>权重</th><th>相对原计划的预测变化</th><th>效用贡献变化</th></tr></thead><tbody>{Object.keys(metrics).map(k=><tr key={k}><td>{metrics[k]}</td><td>{(100*r.objective.weights[k]).toFixed(0)}%</td><td>{['profit','welfare','cash'].includes(k)?`¥${((selected.metrics[k]-original.metrics[k])/100).toFixed(2)}`:(selected.metrics[k]-original.metrics[k]).toFixed(2)}</td><td>{(selected.contributions[k]-original.contributions[k]).toFixed(5)}</td></tr>)}</tbody></table></>}
 <h3>相对原计划改变了什么</h3>{changes.length?<table><thead><tr><th>字段</th><th>原计划</th><th>建议</th></tr></thead><tbody>{changes.map(k=><tr key={k}><td>{k}</td><td>{JSON.stringify(r.draft_action[k])}</td><td>{JSON.stringify(r.action[k])}</td></tr>)}</tbody></table>:<p>可执行原计划保持不变。弃权不表示原计划没有风险。</p>}
 <h3>独立模拟验证</h3><p>这里的下界针对当前预测模型，不是现实盈利保证。对手本轮看不到候选动作，条件响应从后续回合开始。</p><table><thead><tr><th>期限</th><th>平均效用增益</th><th>模型内95%下界</th><th>负样本</th><th>门槛</th></tr></thead><tbody>{r.validation.map((v,i)=><tr key={i}><td>{v.horizon}轮</td><td>{v.mean_gain.toFixed(5)}</td><td>{v.lower_bound.toFixed(5)}</td><td>{v.negative_samples}/8</td><td>{v.pass_gate?'通过':'未通过'}</td></tr>)}</tbody></table>
 <p>耗时{r.search.elapsed_seconds.toFixed(2)}秒；使用{r.search.used_steps}/{r.search.step_budget}步；检查{r.search.complete?'完整':'未完成'}。</p><p>{r.continuation}</p>
 <details><summary>原计划、候选与模型依据</summary><p>响应模型：{r.response_model}；版本校验：{r.model_sha256}</p><pre>{JSON.stringify({draft:r.draft_action,selected:r.action,candidates:r.candidates},null,2)}</pre></details><ul>{r.limitations.map(x=><li key={x}>{x}</li>)}</ul></article>;
}
