"use client";
import {useEffect,useRef,useState,type ReactNode} from 'react';
import {AdvisorResult,goalLabels,phaseLabels,metricLabels} from './advisor-v16';
import {RecordedFields} from './research-live';
import {restoreTheoryParameters} from './theory-parameters';

const kinds:Record<string,string>={advisor:'目标驱动博弈建议',matrix:'收益矩阵与均衡',repeated:'重复博弈与互惠',learning:'策略学习与遗憾',sequential:'序贯行动与承诺',information:'贝叶斯信息价值',bargaining:'议价与分歧点',public_goods:'公共品与搭便车',market_matrix:'市场反事实'};
const games:Record<string,{title:string;labels:string[];payoffs:number[][][]}>= {
 prisoners_dilemma:{title:'囚徒困境',labels:['合作','背叛'],payoffs:[[[3,3],[0,5]],[[5,0],[1,1]]]},
 stag_hunt:{title:'猎鹿博弈',labels:['猎鹿','猎兔'],payoffs:[[[4,4],[0,3]],[[3,0],[3,3]]]},
 chicken:{title:'胆小鬼博弈',labels:['退让','坚持'],payoffs:[[[3,3],[1,4]],[[4,1],[0,0]]]},
 matching_pennies:{title:'匹配硬币',labels:['正面','反面'],payoffs:[[[1,-1],[-1,1]],[[ -1,1],[1,-1]]]}
};
const strategies:Record<string,string>={cooperate:'始终合作',defect:'始终背叛',tit_for_tat:'针锋相对',grim_trigger:'冷酷触发',generous_tft:'宽容互惠',win_stay_lose_shift:'赢留输换'};
const findings:Record<string,string>={'29':'四个经典矩阵验收通过：囚徒困境的个体稳定点并非共同最优，匹配硬币需要随机化。','30':'576局对照：执行噪声显著改变互惠与触发策略收益，排名依赖对手人口。','31':'64组、19.2万轮：外部遗憾与CCE缺口一致；经验联合分布与边际纳什分别检验。','32':'81组条件：承诺、信号与分歧点会改变决策；离散数量存在多个同时行动均衡。','33':'48局实际市场：最佳回应和保底提高平均公司利润但降低总福利；价格互惠8个种子均落后规则。','34':'两家真实模型6次诊断全部成功，明确选项下偏离损失为0；仅说明这6道局部问题，不能推出长期最优。'};
type Cell={row:number;column:number;payoffs:number[];deviation_gains:number[];best_responses:boolean[];pareto:boolean};
type Result={kind:string;scope?:string;information_scope?:string;labels?:string[];payoffs?:number[][][];cells?:Cell[];pure_nash?:number[][];interior_mixed_nash?:{row_probability:number;column_probability:number;payoffs:number[];exact:string[]}[];security?:{player:number;first_probability:number;guaranteed_payoff:number}[];strictly_dominated?:{player:number;action:number;by:number}[];degenerate?:boolean;[key:string]:unknown};
type HistoryPage={experiments:Saved[];issues?:{id:string;message:string}[];next_offset?:number|null;total?:number};
type Saved={id:string;created:string;sha256:string;request:{kind:string;parameters:Record<string,unknown>};result?:Result};
function savedSummary(s:Saved){const p=restoreTheoryParameters(s.request.kind,s.request.parameters);return [s.request.kind==='advisor'?`${p.advisor_version||'v16'} · ${goalLabels[String(p.goal)]} · ${phaseLabels[String(p.phase)]} · ${p.company_id} · ${p.company_count||'当前'}家 · 预测${p.horizon}轮`:null,typeof p.game==='string'?games[p.game]?.title:null,p.algorithm==='fictitious_play'?'虚拟对弈':p.algorithm==='regret_matching'?'遗憾匹配':null,typeof p.row==='string'?strategies[p.row]:null,typeof p.column==='string'?strategies[p.column]:null,typeof p.rounds==='number'?`${p.rounds}轮`:null,typeof p.seed==='number'?`种子 ${p.seed}`:null,`记录 ${s.id.slice(0,8)}`].filter(Boolean).join(' · ');}
const num=(v:unknown)=>typeof v==='number'?Number(v.toFixed(5)).toLocaleString('zh-CN'):v===null?'不可能发生':String(v??'—');
const array=(r:Result,key:string)=>r[key] as Record<string,unknown>[]|undefined;
function Table({headers,rows}:{headers:string[];rows:ReactNode[][]}){return <div className="v10-table-scroll"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{row.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table></div>;}
function Trend({rows,keys,labels}:{rows:Record<string,unknown>[];keys:string[];labels:string[]}){
 const vals=rows.flatMap(r=>keys.map(k=>Number(r[k])));const maximum=Math.max(1,...vals),minimum=Math.min(0,...vals);const colors=['#1976a3','#bb603b'];
 return <figure className="theory-trend"><svg viewBox="0 0 700 160" role="img" aria-label={labels.join('与')+'随回合变化'}><line x1="35" y1="130" x2="680" y2="130" stroke="#b8c5cc"/><text x="0" y="20">{num(maximum)}</text><text x="0" y="130">{num(minimum)}</text>{keys.map((key,k)=><polyline key={key} fill="none" stroke={colors[k]} strokeWidth="2.5" points={rows.map((r,i)=>`${35+i/Math.max(1,rows.length-1)*645},${130-(Number(r[key])-minimum)/(maximum-minimum)*110}`).join(' ')}/>)}<text x="35" y="153">第1轮</text><text x="575" y="153">第{num(rows.at(-1)?.round)}轮</text></svg><figcaption>{labels.map((label,k)=><span key={label} style={{color:colors[k]}}>● {label} </span>)}</figcaption></figure>;
}
function Matrix({r}:{r:Result}){
 const [selected,setSelected]=useState(0);const cells=r.cells||[];const cell=cells[selected]||cells[0];const labels=r.labels||['动作1','动作2'];
 return <><p>每格依次是 A、B 收益。蓝色收益表示对此对手动作的最佳回应；双边最佳回应就是纯纳什。帕累托标记只比较四个纯动作结果，不包含随机化组合。点击一格查看偏离动机。</p><div className="theory-matrix"><span>A ↓ / B →</span>{labels.map(l=><strong key={l}>{l}</strong>)}{[0,1].map(i=><div className="theory-matrix-row" key={i}><strong>{labels[i]}</strong>{[0,1].map(j=>{const c=cells[i*2+j];return <button key={j} className={selected===i*2+j?'selected':''} onClick={()=>setSelected(i*2+j)} aria-label={`收益格 A${i+1} B${j+1}`}><span className={c?.best_responses[0]?'best':''}>{num(c?.payoffs[0])}</span> / <span className={c?.best_responses[1]?'best':''}>{num(c?.payoffs[1])}</span><small>{c?.best_responses.every(Boolean)?'纯纳什 ':''}{c?.pareto?'纯动作帕累托有效':''}</small></button>;})}</div>)}</div>
 {cell&&<div className="theory-note">当前格：A 可单独改进 {num(cell.deviation_gains[0])}，B 可单独改进 {num(cell.deviation_gains[1])}。{cell.deviation_gains.some(g=>g>0)?'至少一方有偏离动机。':'双方在这个有限动作集合内均无获利偏离。'}</div>}
 <p>纯纳什：{r.pure_nash?.length?r.pure_nash.map(([i,j])=>`（${labels[i]}，${labels[j]}）`).join('、'):'没有'}。{r.degenerate?'存在退化情形，可能有连续或边界混合均衡；这里不声称穷尽。':''}</p>
 {r.interior_mixed_nash?.map((s,i)=><p key={i}>内部混合均衡：A 选择第一个动作的概率 {s.exact[0]}，B 为 {s.exact[1]}；期望收益 {s.payoffs.map(num).join(' / ')}。</p>)}
 <Table headers={['玩家','保底随机策略：首动作概率','可保证的最低收益']} rows={(r.security||[]).map(s=>[s.player===0?'A':'B',num(s.first_probability),num(s.guaranteed_payoff)])}/>
 <p>严格被支配动作：{r.strictly_dominated?.length?r.strictly_dominated.map(d=>`${d.player===0?'A':'B'} 的${labels[d.action]}`).join('、'):'没有'}。纳什是稳定性条件，帕累托是相互改进条件，二者不同。</p></>;
}
function ResultView({r}:{r:Result}){
 if(r.kind==='matrix'||r.kind==='market_matrix')return <Matrix r={r}/>;
 if(r.kind==='repeated'){
  const history=array(r,'history')||[];const total=history.map(h=>{const a=h.actions as number[];return {...h,a:1-a[0],b:1-a[1]};});
  return <><p>平均收益 A / B：{(r.average_payoffs as number[]).map(num).join(' / ')}；折扣平均：{(r.discounted_payoffs as number[]).map(num).join(' / ')}。</p><p>合作率 A / B：{(r.cooperation_rate as number[]).map(v=>`${num(v*100)}%`).join(' / ')}。无限期冷酷触发阈值 δ≥0.5；有限已知轮数的结果需另作解释。</p><Trend rows={total} keys={['a','b']} labels={['A合作=1','B合作=1']}/><details open><summary>逐轮策略意图、执行噪声和收益</summary><Table headers={['轮次','意图 A/B','执行 A/B','噪声 A/B','收益 A/B']} rows={history.map(h=>[num(h.round),(h.intended as number[]).map(v=>v?'背叛':'合作').join('/'),(h.actions as number[]).map(v=>v?'背叛':'合作').join('/'),(h.trembles as boolean[]).map(v=>v?'翻转':'无').join('/'),(h.payoffs as number[]).map(num).join('/')])}/></details></>;
 }
 if(r.kind==='learning')return <><div className="theory-note">经验联合分布的 CCE 缺口：{num(r.cce_gap)}。越小表示固定单边偏离的收益越小。</div><p>边际乘积分布的纳什偏离收益 A/B：{(r.marginal_nash_gains as number[]).map(num).join(' / ')}。两个诊断不应互相替代。</p><Trend rows={array(r,'history')||[]} keys={['row_first_frequency','column_first_frequency']} labels={['A首动作累计频率','B首动作累计频率']}/><Table headers={['A动作 / B动作','B1概率','B2概率']} rows={(r.joint_distribution as number[][]).map((row,i)=>[`A${i+1}`,...row.map(num)])}/><details><summary>每个时间点的遗憾证据</summary><RecordedFields value={r.history}/></details></>;
 if(r.kind==='sequential')return <><h3>同时行动的数量均衡</h3><Table headers={['A/B数量','A/B收益']} rows={(array(r,'simultaneous_nash')||[]).map(x=>[(x.quantities as number[]).join('/'),(x.payoffs as number[]).join('/')])}/><h3>承诺数量后的最优结果</h3><Table headers={['先行者数量','跟随者数量','双方收益']} rows={(array(r,'commitment_solutions')||[]).map(x=>[num(x.leader_quantity),num(x.selected_follower),(x.payoffs as number[]).join('/')])}/><details><summary>展开逐个承诺的逆向归纳</summary><Table headers={['承诺数量','跟随者最佳回应集合','双方收益']} rows={(array(r,'tree')||[]).map(x=>[num(x.leader_quantity),(x.follower_responses as number[]).join(','),(x.payoffs as number[]).join('/')])}/></details></>;
 if(r.kind==='information')return <><div className="theory-note">弱对手后验概率超过 {num(Number(r.entry_threshold)*100)}% 时进入有正期望收益。</div><Table headers={['信号','发生概率','弱对手后验','进入期望收益','最佳行动']} rows={(array(r,'signals')||[]).map(s=>[s.signal==='weak_signal'?'偏弱信号':'偏强信号',num(s.probability),num(s.posterior_weak),num(s.entry_payoff),s.action==='enter'?'进入':s.action==='stay'?'不进入':'不可能发生'])}/><p>不看信号的最佳收益 {num(r.without_information)}；看信号 {num(r.with_information)}；信息价值 {num(r.value_of_information)}；完美信息价值上界 {num(r.perfect_information_bound)}。若购买信息，最多愿付其增量价值。</p></>;
 if(r.kind==='bargaining')return <><p>分歧点 A/B：{(r.disagreement as number[]).join('/')}；可分配剩余 {num(r.surplus)}。权重改变剩余增益的分配。</p><Table headers={['A/B分配','相对分歧点增益','加权Nash乘积']} rows={(array(r,'solutions')||[]).map(s=>[(s.allocation as number[]).join('/'),(s.gains as number[]).join('/'),num(s.score)])}/>{!(array(r,'solutions')||[]).length&&<p>不存在同时满足双方分歧点的可行协议。</p>}<details><summary>全部可行分配</summary><RecordedFields value={r.feasible}/></details></>;
 if(r.kind==='public_goods')return <><p>单人贡献的个人边际收益 {num(r.individual_marginal_return)}，社会边际收益 {num(r.social_marginal_return)}。这一差距产生搭便车动机。</p><Table headers={['各人贡献（1/0）','各人期末资源','总收益','纯纳什']} rows={(array(r,'outcomes')||[]).map(s=>[(s.actions as number[]).join(' / '),(s.payoffs as number[]).map(num).join(' / '),num(s.total_payoff),s.pure_nash?'是':'否'])}/></>;
 return null;
}

export function TheoryLab({apiUrl,token,episodeId,onWorkbench}:{apiUrl:string;token:string;episodeId:string;onWorkbench:()=>void}){
 const [kind,setKind]=useState('advisor'),[game,setGame]=useState('prisoners_dilemma'),[payoffs,setPayoffs]=useState(games.prisoners_dilemma.payoffs),[row,setRow]=useState('tit_for_tat'),[column,setColumn]=useState('defect'),[algorithm,setAlgorithm]=useState('regret_matching');
 const [values,setValues]=useState<Record<string,number>>({company_count:4,market_rounds:10,horizon:3,scenarios:3,max_candidates:16,step_budget:1800,risk_aversion:.25,cash_floor_cents:0,w_profit:50,w_welfare:50,w_cash:0,w_share:0,w_capacity:0,w_resilience:0,rounds:60,seed:340101,noise:.1,discount:.95,intercept:30,cost:6,maximum:24,weak_prior:.5,accuracy:.8,win:8,loss:6,surplus:100,disagreement_row:20,disagreement_column:10,weight:.5,players:4,endowment:10,contribution:4,multiplier:1.6});
 const [advisorVersion,setAdvisorVersion]=useState('v17');
 const [goal,setGoal]=useState('company'),[phase,setPhase]=useState('auto'),[company,setCompany]=useState('company_A'),[diagnostics,setDiagnostics]=useState(true),[backtest,setBacktest]=useState(true);
 const [record,setRecord]=useState<Saved|null>(null),[saved,setSaved]=useState<Saved[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[useCurrent,setUseCurrent]=useState(true),[reports,setReports]=useState<Record<string,unknown>>({});
 const [nextOffset,setNextOffset]=useState<number|null>(null),[historyIssues,setHistoryIssues]=useState<{id:string;message:string}[]>([]),[historyBusy,setHistoryBusy]=useState(false);
 const resultRef=useRef<HTMLElement|null>(null);
 useEffect(()=>{if(record)resultRef.current?.scrollIntoView({block:'start'});},[record]);
 const base=`${apiUrl}/v1/controller/theory-lab`;const headers={'Content-Type':'application/json',...(token?{'X-Controller-Token':token}:{})};
 useEffect(()=>{let live=true;void fetch(`${apiUrl}/v1/controller/theory-lab/experiments`,{headers:token?{'X-Controller-Token':token}:{}}).then(async r=>{if(!r.ok)throw new Error(await r.text());return r.json();}).then(v=>{if(live){const page=v as HistoryPage;setSaved(page.experiments);setNextOffset(page.next_offset??null);setHistoryIssues(page.issues||[]);}}).catch(e=>{if(live)setError(String(e));});return()=>{live=false;};},[apiUrl,token]);
 const field=(key:string,label:string,min:number,max:number,step=1)=><label key={key}>{label}<input type="number" min={min} max={max} step={step} value={values[key]} onChange={e=>setValues({...values,[key]:Number(e.target.value)})}/></label>;
 const selectGame=<label>博弈情境<select value={game} onChange={e=>{setGame(e.target.value);setPayoffs(games[e.target.value].payoffs);}}>{Object.entries(games).map(([k,v])=><option key={k} value={k}>{v.title}</option>)}</select></label>;
 const pick=(...keys:string[])=>Object.fromEntries(keys.map(k=>[k,values[k]]));
 async function moreHistory(){if(nextOffset===null)return;setHistoryBusy(true);try{const r=await fetch(`${base}/experiments?offset=${nextOffset}`,{headers});if(!r.ok)throw new Error(await r.text());const page=await r.json() as HistoryPage;setSaved(old=>Array.from(new Map([...old,...page.experiments].map(v=>[v.id,v])).values()));setNextOffset(page.next_offset??null);setHistoryIssues(old=>[...old,...(page.issues||[])]);}catch(e){setError(String(e));}finally{setHistoryBusy(false);}}
 async function run(){setBusy(true);setError('');try{
  if(kind==='advisor'&&goal==='custom'&&Math.abs(Object.keys(metricLabels).reduce((sum,k)=>sum+values['w_'+k],0)-100)>1e-6)throw new Error('各项目标权重合计必须为100%。');
  const parameters=kind==='advisor'?{advisor_version:advisorVersion,goal,phase,company_id:company,diagnostics,backtest,...pick('company_count','market_rounds','horizon','scenarios','max_candidates','step_budget','risk_aversion','cash_floor_cents','seed','discount'),...(goal==='custom'?{weights:Object.fromEntries(Object.keys(metricLabels).map(k=>[k,values['w_'+k]/100]))}:{}),...(useCurrent&&episodeId?{episode_id:episodeId}:{})}:kind==='matrix'?{game,payoffs}:kind==='repeated'?{row,column,...pick('rounds','seed','noise','discount')}:kind==='learning'?{game,algorithm,...pick('rounds','seed')}:kind==='sequential'?pick('intercept','cost','maximum'):kind==='information'?pick('weak_prior','accuracy','win','loss'):kind==='bargaining'?pick('surplus','disagreement_row','disagreement_column','weight'):kind==='public_goods'?pick('players','endowment','contribution','multiplier'):{seed:values.seed,...(useCurrent&&episodeId?{episode_id:episodeId}:{})};
  const response=await fetch(`${base}/experiments`,{method:'POST',headers,body:JSON.stringify({request_id:crypto.randomUUID(),kind,parameters})});if(!response.ok)throw new Error(await response.text());const result=await response.json() as Saved;setRecord(result);setSaved([result,...saved]);
 }catch(e){setError(String(e));}finally{setBusy(false);}}
 async function load(id:string){setBusy(true);try{
  const response=await fetch(`${base}/experiments/${id}`,{headers});if(!response.ok)throw new Error(await response.text());
  const restored=await response.json() as Saved;const p=restoreTheoryParameters(restored.request.kind,restored.request.parameters);
  setRecord(restored);setKind(restored.request.kind);
  if(restored.request.kind==='advisor'){setAdvisorVersion(String(p.advisor_version||'v16'));setGoal(String(p.goal));setPhase(String(p.phase));setCompany(String(p.company_id));setDiagnostics(Boolean(p.diagnostics));setBacktest(Boolean(p.backtest));if(p.weights&&typeof p.weights==='object')setValues(v=>({...v,...Object.fromEntries(Object.entries(p.weights as Record<string,number>).map(([k,w])=>['w_'+k,w*100]))}));}
  setValues(v=>({...v,...Object.fromEntries(Object.entries(p).filter((entry):entry is [string,number]=>typeof entry[1]==='number'))}));
  if(typeof p.game==='string'&&games[p.game]){setGame(p.game);setPayoffs(games[p.game].payoffs);}
  if(Array.isArray(p.payoffs))setPayoffs(p.payoffs as number[][][]);
  if(typeof p.row==='string')setRow(p.row);if(typeof p.column==='string')setColumn(p.column);
  if(typeof p.algorithm==='string')setAlgorithm(p.algorithm);
  setUseCurrent(Boolean(p.episode_id&&p.episode_id===episodeId));
  setError(p.episode_id&&p.episode_id!==episodeId?'历史结果已恢复。若要复跑该市场状态，请先在主页面恢复其原市场存档；当前表单将使用新市场种子。':'');
 }catch(e){setError(String(e));}finally{setBusy(false);}}
 async function download(){if(!record)return;try{const response=await fetch(`${base}/experiments/${record.id}`,{headers});if(!response.ok)throw new Error(await response.text());const url=URL.createObjectURL(await response.blob());const a=document.createElement('a');a.href=url;a.download=`theory-${record.id}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(String(e));}}
 async function readReports(){try{const r=await fetch(`${base}/acceptance`,{headers});if(!r.ok)throw new Error(await r.text());setReports(await r.json());}catch(e){setError(String(e));}}
 return <section className="theory-lab card"><header><span className="theory-eyebrow">策略研究 · 从假设到可检验结论</span><h1>博弈策略实验室</h1><p>先看对手行动如何改变收益，再选择策略并检验。所有概念计算免费、自动保存；市场策略可在批量工作台中实际运行。</p><button onClick={onWorkbench}>进入市场策略对照实验 →</button></header>
 <nav aria-label="博弈论概念">{Object.entries(kinds).map(([key,label])=><button aria-pressed={kind===key} key={key} onClick={()=>{setKind(key);setRecord(null);setError('');if(key==='learning')setValues(v=>({...v,rounds:3000}));else if(key==='repeated')setValues(v=>({...v,rounds:60}));}}>{label}</button>)}</nav>
 <div className="theory-workspace"><form onSubmit={e=>{e.preventDefault();void run();}}><h2>设定：{kinds[kind]}</h2><div className="theory-controls">
 {kind==='advisor'&&<><label>建议算法<select value={advisorVersion} onChange={e=>setAdvisorVersion(e.target.value)}><option value="v17">v17 反击感知建议（实验性）</option><option value="v16">v16 目标建议（对照）</option></select></label><p>v17把对手反击纳入筛选；当前存档自动读取决策前公开价格历史，新市场没有历史时使用先验。有限反击检查不能保证均衡或不亏损。</p><label>优化目标<select value={goal} onChange={e=>setGoal(e.target.value)}>{Object.entries(goalLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>公司阶段<select value={phase} onChange={e=>setPhase(e.target.value)}>{Object.entries(phaseLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>目标公司<select value={company} onChange={e=>setCompany(e.target.value)}>{Array.from({length:10},(_,i)=>`company_${String.fromCharCode(65+i)}`).map(id=><option key={id}>{id}</option>)}</select></label>{field('company_count','新市场公司数量',2,10)}<label>新市场回合数<select value={values.market_rounds} onChange={e=>setValues({...values,market_rounds:Number(e.target.value)})}>{[5,10,15,20,60].map(n=><option key={n}>{n}</option>)}</select></label>{field('horizon','预测轮数',1,10)}{field('scenarios','搜索与验证各自情景数',2,8)}{field('max_candidates','候选数量上限',4,48)}{field('step_budget','引擎计算步数上限',100,12000)}{field('risk_aversion','样本下行风险权重',0,2,.05)}{field('discount','未来每轮折扣',.01,1,.01)}{field('cash_floor_cents','现金底线（分）',0,1000000000)}{field('seed','实验随机种子',0,2147483647)}{goal==='custom'&&Object.keys(metricLabels).map(k=>field('w_'+k,metricLabels[k]+'权重（%，合计100）',0,100))}<label><input type="checkbox" checked={diagnostics} onChange={e=>setDiagnostics(e.target.checked)}/>多人博弈与联合福利诊断</label><label><input type="checkbox" checked={backtest} onChange={e=>setBacktest(e.target.checked)}/>独立复制市场执行对照（不推进原市场）</label>{episodeId&&<label><input type="checkbox" checked={useCurrent} onChange={e=>setUseCurrent(e.target.checked)}/>使用当前实验状态；人数与回合数取当前市场</label>}<p>建议为本公司的单边可执行行动。联合福利方案单独展示，不假定其他主体接受。计算步数包含搜索、验证、诊断和事后对照；免费、不调用模型。</p></>}
 {kind==='matrix'&&<>{selectGame}{payoffs.map((r,i)=>r.map((c,j)=>c.map((v,k)=><label key={`${i}${j}${k}`}>{k===0?'A':'B'} 收益：{games[game].labels[i]} / {games[game].labels[j]}<input aria-label={`${k===0?'A':'B'} ${i+1}${j+1}收益`} type="number" min={-1000000000} max={1000000000} step="any" value={v} onChange={e=>setPayoffs(payoffs.map((r,x)=>r.map((c,y)=>c.map((old,z)=>x===i&&y===j&&z===k?Number(e.target.value):old))))}/></label>)))}</>}
 {kind==='repeated'&&<><label>A策略<select value={row} onChange={e=>setRow(e.target.value)}>{Object.entries(strategies).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></label><label>B策略<select value={column} onChange={e=>setColumn(e.target.value)}>{Object.entries(strategies).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></label>{field('rounds','重复轮数',1,500)}{field('noise','执行翻转概率',0,.5,.01)}{field('discount','每轮折扣因子',0,1,.01)}{field('seed','随机种子',0,2147483647)}</>}
 {kind==='learning'&&<>{selectGame}<label>学习算法<select value={algorithm} onChange={e=>setAlgorithm(e.target.value)}><option value="regret_matching">外部遗憾匹配</option><option value="fictitious_play">虚拟对弈</option></select></label>{field('rounds','学习轮数',10,10000)}{field('seed','随机种子',0,2147483647)}</>}
 {kind==='sequential'&&<>{field('intercept','需求截距',1,1000)}{field('cost','单位成本',0,999)}{field('maximum','数量上限',1,60)}</>}
 {kind==='information'&&<>{field('weak_prior','弱对手先验概率',0,1,.05)}{field('accuracy','信号准确率',.5,1,.05)}{field('win','面对弱对手的收益',1,1000)}{field('loss','面对强对手的损失',1,1000)}</>}
 {kind==='bargaining'&&<>{field('surplus','可分配剩余',1,1000)}{field('disagreement_row','A分歧收益',0,1000)}{field('disagreement_column','B分歧收益',0,1000)}{field('weight','A议价权重',.01,.99,.01)}</>}
 {kind==='public_goods'&&<>{field('players','参与人数',2,8)}{field('endowment','每人初始资源',1,100)}{field('contribution','贡献成本',1,100)}{field('multiplier','总公共收益倍数',1.01,7.99,.01)}</>}
 {kind==='market_matrix'&&<>{field('seed','新市场随机种子',0,2147483647)}{episodeId&&<label><input type="checkbox" checked={useCurrent} onChange={e=>setUseCurrent(e.target.checked)}/>使用当前实验；已结束时使用最后一轮结算前状态</label>}<p>比较公司 A/B 的基线与降价策略，其他公司保持基线。研究者可读完整状态；此收益表不会泄露给公司策略。收益单位为分。</p></>}
 </div><button className="theory-run" disabled={busy} type="submit">{busy?'计算并保存中…':'运行并保存实验'}</button></form>
 <section ref={resultRef} className="theory-result" aria-label="博弈实验结果">{error&&<p role="alert">{error}</p>}{record?.result?<><div className="theory-result-head"><h2>{kinds[record.request.kind]} · 已保存</h2><button onClick={()=>void download()}>导出完整实验 JSON</button></div><p className="theory-assumptions">{record.result.information_scope||record.result.scope}</p>{record.request.kind==='advisor'?<AdvisorResult value={record.result}/>:<ResultView key={record.id} r={record.result}/>}<details><summary>查看假设、输入与校验记录</summary><RecordedFields value={{request:record.request,sha256:record.sha256}}/></details></>:<div className="theory-empty"><h2>把策略变成可检验的选择</h2><p>设置参数后运行，查看收益、偏离动机与适用条件。概念实验的数值不代表现实市场预测。</p></div>}</section></div>
 <section className="theory-archive"><h2>已保存的概念实验</h2>{!saved.length?<p>运行首个实验后会自动出现在这里，关闭页面也会保留。</p>:<div>{saved.map(s=><button key={s.id} disabled={busy} onClick={()=>void load(s.id)}><span>{kinds[s.request.kind]} · {new Date(s.created).toLocaleString('zh-CN')}</span><small>{savedSummary(s)}</small></button>)}</div>}{nextOffset!==null&&<button disabled={historyBusy} onClick={()=>void moreHistory()}>{historyBusy?'读取中…':'加载更早的实验'}</button>}{historyIssues.map(issue=><p role="status" key={issue.id}>记录 {issue.id.slice(0,8)}：{issue.message}</p>)}</section>
 <section><h2>阶段验收与实际模型证据</h2><button onClick={()=>void readReports()}>读取已完成实验结论</button>{Object.entries(reports).map(([stage,report])=><section key={stage}><h3>阶段 {stage}</h3><p>{findings[stage]||'v16独立阶段验收；展开查看通过项、样本规模与限制。'}</p><details><summary>查看本阶段验收数据</summary><RecordedFields value={report}/></details></section>)}<p>市场模式的最佳回应/保底基于公开信息预测；互惠和触发是有限策略启发式。实际模型只按原预算执行，允许调用不代表提高预算。</p></section></section>;
}
